project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "*.md"
    - "!slides/quarto/sample/*.qmd"

website:
  site-url: "https://nbisweden.github.io/raukr-2026/"
  open-graph: true
  description: "An intensive workshop covering the R ecosystem including best coding practices, code profiling, data wrangling, quarto notebooks, shiny apps and more."
  image: "assets/images/seo.webp"
  favicon: "assets/favicon.svg"
  navbar:
    logo: "assets/logos/raukr.png"
    logo-alt: "RaukR"
    right:
      - text: "Home"
        href: "index.html"
        aria-label: "Home"
      - text: "Program"
        href: "home_program.html"
        aria-label: "Program"
      - text: "Application"
        href: "home_application.html"
        aria-label: "Application"
      - text: Gallery
        href: "home_gallery.html"
        aria-label: "Gallery"
      - text: FAQ
        href: "home_faq.html"
        aria-label: "FAQ"
      - text: About
        href: "home_about.html"
        aria-label: "About"
      - icon: github
        href: https://github.com/NBISweden/raukr-2026
        aria-label: "GitHub"
  page-footer:
    border: false
    left: '{{< meta current_year >}} NBIS • [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)'
    right: "Published with [Quarto](https://quarto.org/) v{{< meta quarto_version >}}"
  announcement:
    icon: info-circle
    dismissable: true
    content: "Registration for RaukR 2026 isn't open yet, but you can sign up to express interest and get notified."
    type: primary
    position: above-navbar

format:
  html:
    quarto-required: ">=1.4.5"
    include-in-header: "assets/include_head.html"
    include-before-body: "assets/include_body_before.html"
    include_after_body: "assets/include_body_after.html"
    theme: "assets/css/styles.scss"
    smooth-scroll: true
    toc: true
    toc-depth: 4
    toc-location: right
    number-sections: true
    number-depth: 4
    code-fold: false
    code-tools: false
    code-copy: true
    code-overflow: wrap
    df-print: paged
    standalone: false
    fig-align: left
    title-block-banner: "assets/images/banner.webp"
    subtitle: "RaukR 2026 • R Beyond the Basics"
    callout-icon: true
    date:  last-modified
    date-format: "DD-MMM-YYYY"
    lightbox:
      match: auto
  revealjs:
    quarto-required: ">=1.4.5"
    include-in-header: "assets/include_head.html"
    include-before-body: "assets/include_body_before.html"
    include_after_body: "assets/include_body_after.html"
    theme: ["default", "assets/css/slides.scss"]
    df-print: kable
    width: 1280
    height: 720
    transition: "fade"
    transition-speed: "fast"
    smaller: false
    incremental: false
    scrollable: false
    slide-level: 2
    slide-number: true
    progress: true
    date:  last-modified
    date-format: "DD-MMM-YYYY"
    fig-align: left
    chalkboard: true
    callout-icon: true
    # hero: "/assets/images/hero.webp"
    title-slide-attributes:
      data-background-image: "/assets/images/cover.webp"
      data-background-size: "cover"
      data-background-opacity: "1"
    subtitle: "RaukR 2026 • R Beyond the Basics"
    header-logo-left: /assets/logos/raukr.svg
    header-logo-left-height: 25px
    header-logo-left-url: https://nbisweden.github.io/raukr-2026/slides/index.html
    header-logo-right: /assets/logos/nbis-scilifelab.svg
    header-logo-right-height: 25px
    header-logo-right-url: https://nbisweden.github.io/raukr-2026/home_contents.html
    template-partials:
      - "/assets/title-slide.html"

execute:
  eval: true
  echo: true
  warning: false
  message: false
  freeze: true

knitr:
  opts_chunk:
    results: hold

filters:
  - assets/custom.lua
  - assets/fold-results.lua
  - reveal-logo
  - fontawesome
  - accordion

